# Generated by Django 4.0.3 on 2022-04-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_movieseance_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieseance',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='movieseance',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
