# Generated by Django 4.0.3 on 2022-04-28 14:45

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_movieseance_image_movieseance_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieseance',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
