# Generated by Django 4.0.3 on 2022-05-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_movieseance_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='/static/421-4212341_default-avatar-svg-hd-png-download.png', upload_to=''),
        ),
    ]
